config/routes.rb
Rails.application.routes.draw do

  root :to=> 'employers/:id', to: 'employers#show'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'employers#new'
  post '/employers' => 'employers#create'
  get '/employers' =>'employers#show'

  resources :employers do
    member do
      get :confirm_email
    end
  end
  get "/phone_verify" => 'phone_verify#new', as: 'new_phone_verify'
  put '/phone_verify' => 'phone_verify#update', as: 'phone_verify'
  post '/phone_verify' => 'phone_verify#create', as: 'resend_phone_verify'
  post '/phone_verify/verify_email' => 'phone_verify#verify_email', as: 'verify_email'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  before_create :confirmation_token
  belongs_to :employer,optional: true
  validates :email,uniqueness: true
  validates :email ,presence: true


  def email_activate
    self.confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private
    def confirmation_token
      if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end
end

app/models/employer.rb
class Employer < ApplicationRecord
  has_secure_password
  has_one :phone,dependent: :destroy
  has_one :email,dependent: :destroy

  validates :name,:location,presence: true

  accepts_nested_attributes_for :phone,allow_destroy: true
  accepts_nested_attributes_for :email,allow_destroy: true

end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :employer,optional: true
  after_update :send_pin!, if: "phone_changed?"

  validates :phone,uniqueness: true
  validates :phone ,presence: true


  def reset_pin!
   self.update_column(:pin, rand(1000..9999))
  end

  def unverify!
    self.update_column(:verified, false)
  end

  def send_pin!
    reset_pin!
    unverify!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_employer
    @current_employer ||= Employer.find(session[:employer_id]) if session[:employer_id]
  end
  helper_method :current_employer

  def authorize
    redirect_to '/login' unless current_employer
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :authorize,only: [:show,:edit]
  def new
    @employer=Employer.new
    @employer.build_email
    @employer.build_phone
  end

  def create
    @employer = Employer.new(employer_params)
    if @employer.save
      session[:employer_id] = @employer.id
      redirect_to root_url(@employer)
    else
      render 'new'
    end
  end

  def edit
    @employer= Employer.find(params[:id])
  end

  def update
    @employer = Employer.find(params[:id])
    if @employer.update_attributes(employer_params)
      flash[:notice] = "Employer credentials updated successfully."
      redirect_to employer_path(@employer)
    else
      render 'edit'
    end
  end

  def show
    @employer = Employer.find(params[:id] || current_employer.id)
  end

  def confirm_email
    employer = Employer.joins(:email).where(emails:{confirm_token: params[:id]}).first

    if employer
      employer.email.email_activate
      flash[:success] = "Welcome ! Your email has been confirmed."
      redirect_to employer_path(employer)
    else
      flash[:error] = "Sorry. Employer does not exist"
      redirect_to '/login'
    end
end


private

  def employer_params
    params.require(:employer).permit(:name, :location, :gender,:password, :password_confirmation,email_attributes:[:email,:id],phone_attributes:[:id,:phone])
  end
end

app/controllers/phone_verify_controller.rb
class PhoneVerifyController < ApplicationController


  # GET /verify
  def new
    resp=SendPinJob.perform_now(current_employer.phone)
    flash.now[:notice] = "A pin has been sent to #{current_employer.phone.phone}. Please verify this number at https://www.twilio.com/console/phone-numbers/verified to get the sms."
  end

  # PUT /verify
  def update
    if Time.now > current_employer.phone.pin_sent_at.advance(minutes: 60)
      flash.now[:alert] = "Your pin has expired. Please request another."
      render :new and return
    elsif params[:pin].try(:to_i) == current_employer.phone.pin
      current_employer.phone.update_attribute(:verified, true)
      redirect_to root_url(current_employer), notice: "Your phone number has been verified!"
    else
      flash.now[:alert] = "The code you entered is invalid."
      render :new
    end
  end

  # POST /verify
  def create
    current_employer.phone.send_pin!
    redirect_to new_verify_url, notice: "A PIN number has been sent to your phone"
  end

  def verify_email
    EmployerMailer.email_verifiaction(current_employer).deliver
    redirect_to root_url(current_employer), notice: "An Email has been sent to #{current_employer.email.email}"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @employer = Employer.new
    @employer.build_email
  end

  def create
    employer = Employer.joins(:email).where(emails:{email:params[:email]}).first
    # If the employer exists AND the password entered is correct.
    if employer && employer.authenticate(params[:password])
        session[:employer_id] = employer.id
        redirect_to employer_path(employer)
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    session[:employer_id] = nil
    redirect_to '/login'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employers/_form.html.erb
<%= form_for @employer,html:{class: 'form-horizontal'} do |f| %>
<% if @employer.errors.any? %>
  <div class="alert alert-danger">
    <a class="close" data-dismiss="alert">&#215;</a>
    <ul>
      <% @employer.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= f.text_field :name ,class: 'input-xlarge',placeholder: 'Name'%>
  <%= f.text_field :location ,class: 'input-xlarge',placeholder: 'Location'%>
  <%= f.label :gender, "Male", :value => "true",class: 'control-label'  %>
  <%= f.radio_button :gender, true %>
  <%= f.label :gender, "Female", :value => "false",class: 'control-label' %>
  <%= f.radio_button :gender, false, :checked => true %>
  <%= f.fields_for :phone do |phone_field| %>
  <%=phone_field.text_field :phone,class: 'input-xlarge',placeholder: 'Phone' %>
  <%end%>
  <%=f.fields_for :email do |email_field| %>
  <%=email_field.text_field :email,class: 'input-xlarge',placeholder: 'Email' %>
  <%end%>
  <% if action_name == 'new' or action_name == 'create' %>
  <%= f.password_field :password ,class: 'input-xlarge',placeholder: 'Password'%>
  <%= f.password_field :password_confirmation ,class: 'input-xlarge',placeholder: 'Password Confirmation'%>
  <%= f.submit "Login" ,class: "login loginmodal-submit"%>
  <% else %>
   <%= hidden_field_tag 'id',@employer.id%>
   <%= f.submit "Update" ,class: "login loginmodal-submit"%>
  <%end%>

<% end %>

app/views/employers/edit.html.erb
<div class="modal-dialog">
<div class="loginmodal-container">
  <h1>Edit Employer</h1><br>
 <%=render 'form' %>
<div class="login-help">
<%= link_to 'Login', '/login' %>
</div>
</div>
</div>

app/views/employers/new.html.erb
<div class="modal-dialog">
<div class="loginmodal-container">
  <h1>Sign-Up Your Account</h1><br>
  <%=render 'form' %>
<div class="login-help">
<%= link_to 'Login', '/login' %>
</div>
</div>
</div>

app/views/employers/show.html.erb
<div class="container">
                <div class="jumbotron">
                  <div class="row">
                      <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                          <img src="https://www.svgimages.com/svg-image/s5/man-passportsize-silhouette-icon-256x256.png" alt="stack photo" class="img">
                      </div>
                      <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                          <div class="container" style="border-bottom:1px solid black">
                            <h2><%= @employer.name%></h2>
                          </div>
                            <hr>
                          <ul class="container details">
                            <li><p><span class="glyphicon glyphicon-earphone one" style="width:50px;"></span><%=@employer.phone.phone %>
                              <%unless @employer.phone.verified%>
                               <%=link_to "verify",resend_phone_verify_url%>
                              <%end%>
                              </p>
                            </li>
                            <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span><%= @employer.email.email%>
                              <% unless current_employer.email.confirmed %>
                               <%=link_to "verify",verify_email_url,method: :post%>
                              <% end %>
                              </p>
                            </li>
                            <li><p><span class="glyphicon glyphicon-map-marker one" style="width:50px;"></span><%=@employer.location%></p></li>
                          </ul>
                      </div>
                  </div>
                </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VerificationApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <%= nav_bar fixed: :top, brand: "Verification App", responsive: true do %>
    <% if current_employer %>
      <%= menu_group pull: :right do %>
        <%= drop_down current_employer.name do %>
                <%= menu_item "Log Out", '/logout' %>
                <%= menu_item "edit", edit_employer_path(current_employer) %>
            <% end %>
        <% end %>
        <% end %>
    <% end %>
    <div class="margin-top120">

    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/phone_verify/new.html.erb
<!-- app/views/sessions/new.html.erb -->



<div class="modal-dialog">
<div class="loginmodal-container">
  <h1>Mobile Verification</h1><br>
  <%= form_for '',url:'/phone_verify', :method => :put,html:{class: 'form-horizontal'} do |f| %>
  <%= f.text_field :pin ,class: 'input-xlarge',placeholder: 'Enter Pin',value: current_employer.phone.pin%>
  <%= f.submit "submit" ,class: "login loginmodal-submit"%>
  <% end%>

</div>
</div>